language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.0
      env:
        - COVERAGE=true

before_install:
  - composer self-update

install:
  - travis_retry composer instal --no-interaction

script:
  - if [[ $COVERAGE == 'true' ]]; then composer coverage ; else composer test ; fi

after_script:
  - if [[ $COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi